/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package auctionserver;

import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.net.*;
import java.util.logging.*;
import javax.swing.*;

/**
 *
 * @author kogayou
 */
public class ServerFrame extends javax.swing.JFrame {

    /**
     * Creates new form ServerFrame
     */
    
    private Thread t;
    
    public ServerFrame() {
        initComponents();
        try {
            ipTextField.setText(InetAddress.getLocalHost().getHostAddress().toString());
        } catch (UnknownHostException ex) {
            Logger.getLogger(ServerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ipLabel = new javax.swing.JLabel();
        portTextField = new javax.swing.JTextField();
        portLabel = new javax.swing.JLabel();
        ipTextField = new javax.swing.JTextField();
        serverToggleButton = new javax.swing.JToggleButton();
        msgLabel = new javax.swing.JLabel();
        msgScrollPane = new javax.swing.JScrollPane();
        msgTextPane = new javax.swing.JTextPane();
        cmdLabel = new javax.swing.JLabel();
        cmdTextField = new javax.swing.JTextField();
        auctionLabel = new javax.swing.JLabel();
        auctionScrollPane = new javax.swing.JScrollPane();
        auctionTextPane = new javax.swing.JTextPane();
        clientLabel = new javax.swing.JLabel();
        clientScrollPane1 = new javax.swing.JScrollPane();
        clientTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("网络拍卖行服务器");

        ipLabel.setText("本机IP地址：");

        portTextField.setText("8000");

        portLabel.setText("端口：");

        ipTextField.setEditable(false);

        serverToggleButton.setText("启动");
        serverToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverToggleButtonActionPerformed(evt);
            }
        });

        msgLabel.setText("消息窗口：");

        msgTextPane.setEditable(false);
        msgScrollPane.setViewportView(msgTextPane);

        cmdLabel.setText("命令行：");

        cmdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdTextFieldKeyPressed(evt);
            }
        });

        auctionLabel.setText("竞拍室信息：");

        auctionTextPane.setEditable(false);
        auctionScrollPane.setViewportView(auctionTextPane);

        clientLabel.setText("竞拍者信息：");

        clientTextPane.setEditable(false);
        clientScrollPane1.setViewportView(clientTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(msgScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(msgLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ipLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(portLabel)
                        .addGap(18, 18, 18)
                        .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmdLabel)
                    .addComponent(cmdTextField))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(auctionLabel)
                    .addComponent(auctionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(clientLabel)
                    .addComponent(clientScrollPane1)
                    .addComponent(serverToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipLabel)
                    .addComponent(portLabel)
                    .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverToggleButton)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgLabel)
                    .addComponent(auctionLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(msgScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdLabel)
                        .addGap(18, 18, 18)
                        .addComponent(cmdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(auctionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clientLabel)
                        .addGap(18, 18, 18)
                        .addComponent(clientScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serverToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverToggleButtonActionPerformed
        // TODO add your handling code here:
        if (serverToggleButton.isSelected()) {
            try {
                ServerKernel.ds=new DatagramSocket(Integer.parseInt(portTextField.getText()));
            } catch (SocketException ex) {
                JOptionPane.showMessageDialog(this,"无法建立UDP套接字，请检查端口号是否正确且未被使用\n"+ex,"出错！",JOptionPane.ERROR_MESSAGE);
                serverToggleButton.setSelected(false);
                return;
            }
            ServerKernel.setTextPanes(msgTextPane,auctionTextPane,clientTextPane);
            t=new Thread(new Runnable() {  
                public void run() {  
                    byte[] buf=new byte[8192];  
                    DatagramPacket dp=new DatagramPacket(buf,8192); 
                    while(true) {  
                        try {   
                            ServerKernel.ds.receive(dp);
                        } catch (IOException ex) {
                            Logger.getLogger(ServerFrame.class.getName()).log(Level.SEVERE, null, ex);
                            continue;                            
                        }
                        ServerKernel.processDatagramPacket(dp);
                    }                  
                }  
            });
            portTextField.setEditable(false);
            ServerKernel.init();
            t.start();
            ServerKernel.appendTextPanes(msgTextPane,"服务器已启动",Color.RED);
        } else {
            t.stop();
            ServerKernel.serverQuit();
            portTextField.setEditable(true);
        }
    }//GEN-LAST:event_serverToggleButtonActionPerformed

    private void cmdTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdTextFieldKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if (!serverToggleButton.isSelected()) {
                JOptionPane.showMessageDialog(this,"请先启动","出错！",JOptionPane.ERROR_MESSAGE);
                return;
            }
            ServerKernel.appendTextPanes(msgTextPane,cmdTextField.getText(),Color.black);
            ServerKernel.processCommand(cmdTextField.getText()+" ");
        }
    }//GEN-LAST:event_cmdTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel auctionLabel;
    private javax.swing.JScrollPane auctionScrollPane;
    private javax.swing.JTextPane auctionTextPane;
    private javax.swing.JLabel clientLabel;
    private javax.swing.JScrollPane clientScrollPane1;
    private javax.swing.JTextPane clientTextPane;
    private javax.swing.JLabel cmdLabel;
    private javax.swing.JTextField cmdTextField;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JTextField ipTextField;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JScrollPane msgScrollPane;
    private javax.swing.JTextPane msgTextPane;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portTextField;
    private javax.swing.JToggleButton serverToggleButton;
    // End of variables declaration//GEN-END:variables
}
